### ISSUE TITLE
Trigger events

### ISSUE THREAD

**Issue by PeterKnee** [aterrien/jQuery-Kontrol#10]
Thanks for sharing, this is a really nice input method.

I might be missing something really simple but if I add a custom hook to the release action, how do I then access the input field properties?

Basically, there is a data validation function linked to the on change function of the input that I want to trigger but I can access any properties of the original field.  this, $(this) etc.

**Comment by aterrien** [comment]
You can use this.$ which is jQuery-wrapped.

**Comment by PeterKnee** [comment]
Thanks Aterrien.

I still can’t get what I’m after though.  If the below line of code was uncommented it returns undefined.  The function does run when the wheel is released.  Could you offer any guidance?

function dialReleased(e){
       console.log('release wheel')
// the id of the input this wheel is linked to.
//this.$.attr(‘id’);

}

**Comment by aterrien** [comment]
The "release" hook can help you :

$(".knob").knob({
     release : function (value) {
          console.log(this.$.attr(‘id’));
     }
);

**Comment by PeterKnee** [comment]
Thanks.  That worked a charm.

My reason for doing this is that I want to validate the entry, using the release hook I now check and reset the value in the input field.  Is there a way I can then trigger a re-draw of the canvas?
